analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    dead_code: info
    invalid_assignment: warning
    missing_return: error

linter:
  rules:
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements